// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGraphData(arg1) {
  return window['go']['main']['App']['GetGraphData'](arg1);
}

export function OpenDatabase(arg1) {
  return window['go']['main']['App']['OpenDatabase'](arg1);
}

export function ProcessFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessFile'](arg1, arg2, arg3, arg4);
}

export function SelectDatabase() {
  return window['go']['main']['App']['SelectDatabase']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
