// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGraphData(arg1:number):Promise<Record<string, any>>;

export function OpenDatabase(arg1:string):Promise<void>;

export function ProcessFile(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SelectDatabase():Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;
